#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-2-Clause-Patent
"""Generate a Linux-only platform overlay; never edit upstream tracked files."""
import argparse
import json
import pathlib
import shutil
import subprocess
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
LOCK = json.loads((HERE / "lock.json").read_text())
PACKAGE = "RedfishEmulatorPkg"


def replace_once(text, old, new):
    if text.count(old) != 1:
        raise ValueError(f"Pinned edk2 source anchor changed: {old!r}")
    return text.replace(old, new, 1)


def prepare(edk2, *, backend=True):
    edk2 = pathlib.Path(edk2).resolve()
    actual = subprocess.check_output(["git", "-C", str(edk2), "rev-parse", "HEAD"], text=True).strip()
    if actual != LOCK["edk2_commit"]:
        raise ValueError(f"Expected edk2 {LOCK['edk2_commit']}, found {actual}")
    # Generated/untracked outputs are fine; changed tracked inputs or submodules
    # would make this a different build despite the expected top-level HEAD.
    changed = subprocess.check_output(["git", "-C", str(edk2), "status", "--porcelain",
                                       "--untracked-files=no", "--ignore-submodules=none"], text=True)
    if changed:
        raise ValueError("edk2 has tracked changes or dirty submodules; use an isolated clean checkout")
    output = edk2 / PACKAGE
    if output.is_symlink():
        raise ValueError(f"Refusing symlinked output: {output}")
    if output.exists() and (not output.is_dir() or not (output / ".generated-by-redfish-client").is_file()):
        raise ValueError(f"Refusing to overwrite unowned directory: {output}")
    if output.exists() and any(path.is_symlink() and path.relative_to(output) != pathlib.Path("Host/X11IncludeHack")
                               for path in output.rglob("*")):
        raise ValueError(f"Refusing symlinks in generated output: {output}")
    # Validate/generate in a fresh tree first. A changed anchor cannot leave a
    # half-updated overlay, and removed sources cannot survive regeneration.
    with tempfile.TemporaryDirectory(prefix=f".{PACKAGE}-", dir=edk2) as temporary:
        generated = pathlib.Path(temporary) / PACKAGE
        _write_overlay(edk2, generated, backend=backend)
        backup = pathlib.Path(temporary) / "previous"
        if output.exists():
            output.rename(backup)
        try:
            generated.rename(output)
        except OSError:
            if backup.exists():
                backup.rename(output)
            raise
    return output


def _write_overlay(edk2, output, *, backend):
    output.mkdir()
    (output / ".generated-by-redfish-client").write_text("Generated by Tools/LinuxEmulator/prepare.py\n")
    shutil.copytree(edk2 / "EmulatorPkg/Unix/Host", output / "Host", dirs_exist_ok=True, ignore=shutil.ignore_patterns("X11IncludeHack"))
    shutil.copytree(edk2 / "EmulatorPkg/Library/PlatformBmLib", output / "PlatformBmLib", dirs_exist_ok=True)
    shutil.copy2(HERE / "Platform/PlatformBmData.c", output / "PlatformBmLib/PlatformBmData.c")
    if backend:
        shutil.copy2(HERE / "Host/LinuxPacketFilter.c", output / "Host/LinuxPacketFilter.c")
    shutil.copytree(HERE / "SmokeTest", output / "SmokeTest", dirs_exist_ok=True)
    # Keep the stack 16-byte aligned at the second Microsoft X64 ABI call.
    # The earlier CopyMem call has three extra pushed arguments; ZeroMem does not.
    shutil.copytree(edk2 / "EmulatorPkg/Sec", output / "Sec")
    switch = output / "Sec/X64/SwitchRam.nasm"
    assembly = switch.read_text()
    marker = "  ; ZeroMem (TemporaryMemoryBase /* rcx */, CopySize /* rdx */);"
    if assembly.count(marker) != 1:
        raise ValueError("Pinned SEC ZeroMem anchor changed")
    before, after = assembly.split(marker)
    after = replace_once(after, "sub     rsp, 0x28", "sub     rsp, 0x20")
    after = replace_once(after, "add     rsp, 0x28", "add     rsp, 0x20")
    switch.write_text(before + marker + after)
    dsc = (edk2 / "EmulatorPkg/EmulatorPkg.dsc").read_text()
    dsc = replace_once(dsc, "PLATFORM_NAME                  = EmulatorPkg", "PLATFORM_NAME                  = RedfishEmulatorPkg")
    dsc = replace_once(dsc, "FLASH_DEFINITION               = EmulatorPkg/EmulatorPkg.fdf", "FLASH_DEFINITION               = RedfishEmulatorPkg/RedfishEmulator.fdf")
    dsc = dsc.replace("Build/Emulator$(ARCH)", "Build/RedfishEmulator$(ARCH)")
    dsc = replace_once(dsc, "!include NetworkPkg/Network.dsc.inc", "!include NetworkPkg/Network.dsc.inc\n!include RedfishClientPkg/RedfishClient.dsc.inc")
    dsc = replace_once(dsc, "!include RedfishPkg/Redfish.dsc.inc", "!include RedfishEmulatorPkg/Redfish.dsc.inc")
    dsc = replace_once(dsc, "EmulatorPkg/Library/PlatformBmLib/PlatformBmLib.inf", "RedfishEmulatorPkg/PlatformBmLib/PlatformBmLib.inf")
    dsc = replace_once(dsc, "EmulatorPkg/Unix/Host/Host.inf", "RedfishEmulatorPkg/Host/Host.inf")
    dsc = replace_once(dsc, 'gEmulatorPkgTokenSpaceGuid.PcdEmuGop|L"GOP Window"', 'gEmulatorPkgTokenSpaceGuid.PcdEmuGop|L""')
    dsc = replace_once(dsc, 'gEmulatorPkgTokenSpaceGuid.PcdEmuNetworkInterface|L"en0"', 'gEmulatorPkgTokenSpaceGuid.PcdEmuNetworkInterface|L"slirp"')
    dsc = replace_once(dsc, 'MAC(000000000000,0x1)', 'MAC(525400123456,0x1)')
    dsc = replace_once(dsc, "GCC:*_*_*_DLINK2_FLAGS == -lpthread -ldl -lXext -lX11", "GCC:*_*_*_DLINK2_FLAGS == -lpthread -ldl -lXext -lX11 $(SLIRP_LIBS)\n  GCC:*_*_*_CC_FLAGS = $(SLIRP_CFLAGS)")
    dsc = replace_once(dsc, "EmulatorPkg/Sec/Sec.inf", "RedfishEmulatorPkg/Sec/Sec.inf")
    dsc += "\n[Components]\n  RedfishEmulatorPkg/SmokeTest/RedfishSmokeTest.inf\n"
    # Fixed host-interface variable-size initialization, confined to this overlay.
    shutil.copytree(edk2 / "EmulatorPkg/Library/RedfishPlatformHostInterfaceLib", output / "RedfishPlatformHostInterfaceLib", dirs_exist_ok=True)
    hi = output / "RedfishPlatformHostInterfaceLib/RedfishPlatformHostInterfaceLib.c"
    code = hi.read_text()
    code = replace_once(code, '  Status = gRT->GetVariable (\n                  L"HostIpAssignmentType",', '  HostIpAssignmentTypeSize = sizeof (HostIpAssignmentType);\n  IpPortDataSize = sizeof (RedfishServiceIpPort);\n  Status = gRT->GetVariable (\n                  L"HostIpAssignmentType",')
    hi.write_text(code)
    dsc = replace_once(dsc, "EmulatorPkg/Library/RedfishPlatformHostInterfaceLib/RedfishPlatformHostInterfaceLib.inf", "RedfishEmulatorPkg/RedfishPlatformHostInterfaceLib/RedfishPlatformHostInterfaceLib.inf")
    # Pinned upstream lifetime fixes are private copies, never source-tree edits.
    for driver in ("RedfishHttpDxe", "RedfishRestExDxe"):
        shutil.copytree(edk2 / "RedfishPkg" / driver, output / driver)
    http = output / "RedfishHttpDxe/RedfishHttpDxe.c"
    code = http.read_text()
    code = replace_once(code, "ZeroMem (BasicAuthString, EncodedAuthStrSize);", "ZeroMem (EncodedAuthString, EncodedAuthStrSize);")
    code = replace_once(code, "Host = AllocateZeroPool (REDFISH_HOST_NAME_MAX);\n    if (AsciiLocation == NULL)", "Host = AllocateZeroPool (REDFISH_HOST_NAME_MAX);\n    if (Host == NULL)")
    http.write_text(code)
    rest = output / "RedfishRestExDxe/RedfishRestExProtocol.c"
    code = rest.read_text()
    code = replace_once(code, "    HttpIoDestroyIo (&(Instance->HttpIo));", "    // Reset configuration while preserving the HTTP child and event lifetime.\n    // DestroyChild owns HttpIoDestroyIo; Configure(NULL) may be repeated.\n    Status = Instance->HttpIo.Http->Configure (Instance->HttpIo.Http, NULL);\n    if (EFI_ERROR (Status)) {\n      goto ON_EXIT;\n    }")
    rest.write_text(code)
    for name in ("Redfish.dsc.inc", "RedfishComponents.dsc.inc", "Redfish.fdf.inc"):
        include = (edk2 / "RedfishPkg" / name).read_text()
        if name == "Redfish.dsc.inc":
            include = replace_once(include, "  !include RedfishPkg/RedfishComponents.dsc.inc", "  !include RedfishEmulatorPkg/RedfishComponents.dsc.inc")
        else:
            for driver in ("RedfishHttpDxe", "RedfishRestExDxe"):
                include = replace_once(include, f"RedfishPkg/{driver}/{driver}.inf", f"RedfishEmulatorPkg/{driver}/{driver}.inf")
        (output / name).write_text(include)
    (output / "RedfishEmulator.dsc").write_text(dsc)
    fdf = (edk2 / "EmulatorPkg/EmulatorPkg.fdf").read_text()
    fdf = replace_once(fdf, "!include RedfishPkg/Redfish.fdf.inc", "!include RedfishEmulatorPkg/Redfish.fdf.inc\n!include RedfishClientPkg/RedfishClient.fdf.inc")
    fdf = replace_once(fdf, "EmulatorPkg/Sec/Sec.inf", "RedfishEmulatorPkg/Sec/Sec.inf")
    (output / "RedfishEmulator.fdf").write_text(fdf)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("edk2", type=pathlib.Path, help="isolated checkout at lock.json edk2_commit")
    args = parser.parse_args()
    try:
        print(prepare(args.edk2))
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        parser.exit(2, f"error: {error}\n")


if __name__ == "__main__":
    main()
